sudo: false

language: node_js
node_js: node

cache:
  directories:
    - tests/elm-stuff/build-artifacts
    - sysconfcpus

before_install:
  if [ ! -d sysconfcpus/bin ];
  then
    git clone https://github.com/obmarg/libsysconfcpus.git;
    cd libsysconfcpus;
    ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
    make && make install;
    cd ..;
  fi
install:
  - npm install

script:
  - npm test
